version: '3'
services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    logging:
      driver: none
    networks:
      app_net:
        ipv4_address: 172.16.86.10

  advanced-cypress-test:
    build: ./04-advanced-cypress-test
    links:
      - app
    environment:
      - CYPRESS_baseUrl=http://172.16.86.10:3000/
    depends_on:
      - app
    networks:
      app_net:
        ipv4_address: 172.16.86.11

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.86.0/24